language: c
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-1.6.5-linux64.tar.xz
  - tar xf arduino-1.6.5-linux64.tar.xz
  - sudo mv arduino-1.6.5 /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino

addons:
  coverity_scan:
    project:
      name: "latonita/arduino-canbus-monitor"
      description: "Build submitted via Travis CI"
    notification_email: latonita@yandex.ru
    build_command_prepend: "cov-configure --comptype gcc --compiler /usr/local/share/arduino/hardware/tools/avr/bin/avr-gcc --template"
    build_command:   "arduino --verify --board arduino:avr:uno arduino-canbus-monitor.ino"
    branch_pattern: coverity_scan

script:
  - arduino --verify --board arduino:avr:uno arduino-canbus-monitor.ino
#  - sonar-scanner
notifications:
  email: false
